# Generated by Django 3.2.12 on 2022-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerdata_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='dist',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
